import { TOKENS } from "@/lib/data";
import { ArrowUpRight, CircleAlert } from "lucide-react";
import Link from "next/link";

export default function Dashboard() {
  const token = TOKENS[0];
  return <main className="shell"><section className="border-x border-b hairline p-6 sm:p-10"><div className="eyebrow">Creator console / {token.creator}</div><div className="mt-5 flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><h1 className="text-4xl sm:text-5xl tracking-[-.05em]">Revenue control</h1><p className="mt-3 text-sm text-[#778087]">Finalized Pump creator fees, separated by trade direction.</p></div><button className="focus-ring border hairline px-4 py-3 mono text-[10px]">CONNECT WALLET</button></div></section>
    <section className="grid grid-cols-2 lg:grid-cols-4 border-x border-b hairline"><Metric label="Total creator fees" value="21.46 SOL"/><Metric label="Buy-generated" value="12.84 SOL" border/><Metric label="Sell-generated" value="8.62 SOL" border/><Metric label="Pending routes" value="2" border/></section>
    <section className="py-14"><div className="flex items-end justify-between border-b hairline pb-5"><div><div className="eyebrow">Treasuries</div><h2 className="mt-3 text-2xl">Vault balances</h2></div><span className="mono text-[10px] text-[#61c997]">● RECONCILED AT SLOT 371,882,104</span></div><div className="mt-5 panel grid lg:grid-cols-[1.1fr_1fr_1fr_auto] items-center"><div className="p-5"><div className="text-lg">${token.symbol}</div><div className="mono mt-2 text-[10px] text-[#687178]">{token.symbol} / SOL</div></div><Vault side="BUY" amount="4,820.00" asset="TSLAX"/><Vault side="SELL" amount="1,936.00" asset="SPCX"/><Link href={`/token/${token.mint}`} className="focus-ring m-4 grid h-10 w-10 place-items-center border hairline"><ArrowUpRight size={14}/></Link></div><div className="mt-4 flex gap-3 border border-[#5c472a] bg-[#1b1710] p-4 text-xs leading-5 text-[#b99a72]"><CircleAlert size={16} className="shrink-0 mt-0.5"/>Live execution is gated until the directional vault program and both mainnet canary paths are verified.</div></section>
  </main>;
}
function Metric({label,value,border}:{label:string;value:string;border?:boolean}) { return <div className={`p-5 sm:p-6 ${border?'border-l':''} hairline`}><div className="eyebrow">{label}</div><div className="number mt-3 text-xl sm:text-2xl">{value}</div></div>; }
function Vault({side,amount,asset}:{side:"BUY"|"SELL";amount:string;asset:string}) { return <div className="border-t lg:border-t-0 lg:border-l hairline p-5"><div className={`eyebrow ${side==='BUY'?'text-[#61c997]!':'text-[#df6b62]!'}`}>{side} vault</div><div className="number mt-2 text-lg">{amount} <small className="text-[10px] text-[#6e777e]">{asset}</small></div></div>; }
